// <auto-generated />
using FoodLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodLibrary.Migrations
{
    [DbContext(typeof(DishContext))]
    partial class DishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FoodLibrary.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"), 1L, 1);

                    b.Property<string>("DishDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            DishDescription = "Bamboo skewers loaded with buffalo and venison",
                            DishName = "Buffalo and venison skewers",
                            Ingredients = "onions | buffalo | venison"
                        },
                        new
                        {
                            DishId = 2,
                            DishDescription = "Fresh kumquat and rye served on a bed of lettuce",
                            DishName = "Kumquat and rye salad",
                            Ingredients = "lettuce | kumquat | rye"
                        },
                        new
                        {
                            DishId = 3,
                            DishDescription = "A crunchy salad featuring gruyere and granola",
                            DishName = "Gruyere and granola salad",
                            Ingredients = "cress | tomato | white cabbage | gruyere | granola"
                        },
                        new
                        {
                            DishId = 4,
                            DishDescription = "Salami and fresh sage served on a bed of lettuce",
                            DishName = "Salami and sage salad",
                            Ingredients = "lettuce | salami | sage"
                        },
                        new
                        {
                            DishId = 5,
                            DishDescription = "A warm, pressed panini filled with crayfish and smoked turkey",
                            DishName = "Crayfish and turkey panini",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | crayfish | turkey"
                        },
                        new
                        {
                            DishId = 6,
                            DishDescription = "A crisp salad featuring fresh cauliflower and butterbean",
                            DishName = "Cauliflower and butterbean salad",
                            Ingredients = "tomato | lettuce | cucumber | cauliflower | butterbean"
                        },
                        new
                        {
                            DishId = 7,
                            DishDescription = "A puff pasty case filled with fresh garlic and potato",
                            DishName = "Garlic and potato pie",
                            Ingredients = "flour | butter | water | salt | onions | garlic | potato"
                        },
                        new
                        {
                            DishId = 8,
                            DishDescription = "Fresh egg tubular pasta in a sauce made from dolcelatte and tubetti",
                            DishName = "Dolcelatte and tubetti penne",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | dolcelatte | tubetti"
                        },
                        new
                        {
                            DishId = 9,
                            DishDescription = "Minced lamb and pigeon stewed",
                            DishName = "Lamb and pigeon casserole",
                            Ingredients = "onion | salt | black pepper | potatoes | lamb | pigeon"
                        },
                        new
                        {
                            DishId = 10,
                            DishDescription = "Thin wonton cases stuffed with garam masala and smoked cheese",
                            DishName = "Garam masala and cheese wontons",
                            Ingredients = "flour | water | salt | onions | garam masala | cheese"
                        },
                        new
                        {
                            DishId = 11,
                            DishDescription = "Thin pastry cases stuffed with baby leek and fresh horseradish",
                            DishName = "Leek and horseradish gyoza",
                            Ingredients = "flour | water | salt | onions | leek | horseradish"
                        },
                        new
                        {
                            DishId = 12,
                            DishDescription = "A crisp salad featuring coconut milk and caviar",
                            DishName = "Coconut milk and caviar salad",
                            Ingredients = "tomato | white cabbage | cucumber | coconut milk | caviar"
                        },
                        new
                        {
                            DishId = 13,
                            DishDescription = "A hot, pressed panini filled with baby onion and corn-fed chicken",
                            DishName = "Onion and chicken panini",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | onion | chicken"
                        },
                        new
                        {
                            DishId = 14,
                            DishDescription = "A crisp salad featuring cumin seeds and fresh loquat",
                            DishName = "Cumin seed and loquat salad",
                            Ingredients = "cucumber | white cabbage | tomato | cumin seed | loquat"
                        },
                        new
                        {
                            DishId = 15,
                            DishDescription = "Fish and butternut squash stewed",
                            DishName = "Fish and squash stew",
                            Ingredients = "onion | salt | black pepper | potatoes | fish | squash"
                        },
                        new
                        {
                            DishId = 16,
                            DishDescription = "Tumeric and chinese cabbage served on a bed of lettuce",
                            DishName = "Tumeric and cabbage salad",
                            Ingredients = "lettuce | tumeric | cabbage"
                        },
                        new
                        {
                            DishId = 17,
                            DishDescription = "A crunchy salad featuring fresh mangetout and blackberry",
                            DishName = "Mangetout and blackberry salad",
                            Ingredients = "tomato | lettuce | cucumber | mangetout | blackberry"
                        },
                        new
                        {
                            DishId = 18,
                            DishDescription = "Spicy vindaloo made with crushed black pepper and fresh squash",
                            DishName = "Black pepper and squash vindaloo",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | squash"
                        },
                        new
                        {
                            DishId = 19,
                            DishDescription = "Lea bacon and socca served on a bed of lettuce",
                            DishName = "Bacon and socca salad",
                            Ingredients = "lettuce | bacon | socca"
                        },
                        new
                        {
                            DishId = 20,
                            DishDescription = "Thin wonton cases stuffed with scallop and rainbow trout",
                            DishName = "Scallop and trout wontons",
                            Ingredients = "flour | water | salt | sugar | scallop | trout"
                        },
                        new
                        {
                            DishId = 21,
                            DishDescription = "A crunchy salad featuring italian seasoning and caraway seeds",
                            DishName = "Italian seasoning and caraway seed salad",
                            Ingredients = "tomato | lettuce | white cabbage | italian seasoning | caraway seed"
                        },
                        new
                        {
                            DishId = 22,
                            DishDescription = "Thin pastry cases stuffed with fresh celeriac and pigeon",
                            DishName = "Celeriac and pigeon dumplings",
                            Ingredients = "flour | water | salt | onions | celeriac | pigeon"
                        },
                        new
                        {
                            DishId = 23,
                            DishDescription = "Thin pastry cases stuffed with garam masala and crab",
                            DishName = "Garam masala and crab dumplings",
                            Ingredients = "flour | water | salt | onions | garam masala | crab"
                        },
                        new
                        {
                            DishId = 24,
                            DishDescription = "Mild curry made with creamed sweetcorn and fresh banana",
                            DishName = "Sweetcorn and banana curry",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | curry leaf | green chilli | sweetcorn | banana"
                        },
                        new
                        {
                            DishId = 25,
                            DishDescription = "Spagetti topped with a blend of fresh cheese and tangy feta",
                            DishName = "Cheese and feta spaghetti",
                            Ingredients = "tomato | passata | onion | garlic | spagetti | oregano | black pepper | cheese | feta"
                        },
                        new
                        {
                            DishId = 26,
                            DishDescription = "Bamboo skewers loaded with marinaded tofu and smoked turkey",
                            DishName = "Tofu and turkey skewers",
                            Ingredients = "onions | tofu | turkey"
                        },
                        new
                        {
                            DishId = 27,
                            DishDescription = "Spicy vindaloo made with pacific cod and fresh anise",
                            DishName = "Cod and anise vindaloo",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | cod | anise"
                        },
                        new
                        {
                            DishId = 28,
                            DishDescription = "Warm ciabatta filled with grouse and fish",
                            DishName = "Grouse and fish ciabatta",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | grouse | fish"
                        },
                        new
                        {
                            DishId = 29,
                            DishDescription = "Nutritional yeast and fresh broccoli served on a bed of lettuce",
                            DishName = "Nutritional yeast and broccoli salad",
                            Ingredients = "lettuce | nutritional yeast | broccoli"
                        },
                        new
                        {
                            DishId = 30,
                            DishDescription = "Sizzling sausages made from black peppercorn and fresh cranberries, served in a roll",
                            DishName = "Peppercorn and cranberry sausages",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | onions | peppercorn | cranberry"
                        },
                        new
                        {
                            DishId = 31,
                            DishDescription = "Thin pastry cases stuffed with mixed peppercorn and chinese cabbage",
                            DishName = "Peppercorn and cabbage gyoza",
                            Ingredients = "flour | water | salt | onions | peppercorn | cabbage"
                        },
                        new
                        {
                            DishId = 32,
                            DishDescription = "A crunchy salad featuring prosciutto and garlic oil",
                            DishName = "Prosciutto and garlic oil salad",
                            Ingredients = "tomato | lettuce | white cabbage | prosciutto | garlic oil"
                        },
                        new
                        {
                            DishId = 33,
                            DishDescription = "Thin and crispy pizza topped with fresh mozzarella and creamy cheese",
                            DishName = "Mozzarella and cheese pizza",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | cheese | mozzarella"
                        },
                        new
                        {
                            DishId = 34,
                            DishDescription = "A crunchy salad featuring fresh daikon and seville orange",
                            DishName = "Daikon and orange salad",
                            Ingredients = "cress | white cabbage | cucumber | daikon | orange"
                        },
                        new
                        {
                            DishId = 35,
                            DishDescription = "Thin pastry cases stuffed with red pesto and smoked salmon",
                            DishName = "Pesto and salmon dumplings",
                            Ingredients = "flour | water | salt | onions | pesto | salmon"
                        },
                        new
                        {
                            DishId = 36,
                            DishDescription = "Spicy vindaloo made with fresh rambutan and goat",
                            DishName = "Rambutan and goat vindaloo",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | rambutan | goat"
                        },
                        new
                        {
                            DishId = 37,
                            DishDescription = "Crunchy stir fry featuring fresh quinoa and courgette",
                            DishName = "Quinoa and courgette stir fry",
                            Ingredients = "garlic | quinoa | courgette"
                        },
                        new
                        {
                            DishId = 38,
                            DishDescription = "Fresh egg tubular pasta in a sauce made from stilton and smoked pancetta",
                            DishName = "Stilton and pancetta penne",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | stilton | pancetta"
                        },
                        new
                        {
                            DishId = 39,
                            DishDescription = "Succulent burgers made from corn-fed chicken and beef, served in a roll",
                            DishName = "Chicken and beef burgers",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | onions | chicken | beef"
                        },
                        new
                        {
                            DishId = 40,
                            DishDescription = "Fresh egg tubular pasta in a sauce made from freshly-caught salmon and fresh avocado",
                            DishName = "Salmon and avocado penne",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | salmon | avocado"
                        },
                        new
                        {
                            DishId = 41,
                            DishDescription = "Medium-hot madras made with fresh mango and hot black pepper",
                            DishName = "Mango and black pepper madras",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | red chilli | tomato | mango | black pepper"
                        },
                        new
                        {
                            DishId = 42,
                            DishDescription = "Hot slices of bread filled with hot black pepper and silken tofu",
                            DishName = "Black pepper and tofu toastie",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | black pepper | tofu"
                        },
                        new
                        {
                            DishId = 43,
                            DishDescription = "Fresh egg pasta in a sauce made from fresh lobster and chunky sausage",
                            DishName = "Lobster and sausage fusilli",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | lobster | sausage"
                        },
                        new
                        {
                            DishId = 44,
                            DishDescription = "Spicy curry made with bell pepper and navratan",
                            DishName = "Pepper and navratan curry",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | curry leaf | green chilli | pepper | navratan"
                        },
                        new
                        {
                            DishId = 45,
                            DishDescription = "Bamboo skewers loaded with duck and fresh mangetout",
                            DishName = "Duck and mangetout skewers",
                            Ingredients = "onions | duck | mangetout"
                        },
                        new
                        {
                            DishId = 46,
                            DishDescription = "Hot vindaloo made with tumeric and asafoetida",
                            DishName = "Tumeric and asafoetida vindaloo",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | black pepper | mustard seeds | cardamon | cinnamon | white wine vinegar | cayenne | asafoetida"
                        },
                        new
                        {
                            DishId = 47,
                            DishDescription = "Creamy risotto rice with gorgonzola and scallop",
                            DishName = "Gorgonzola and scallop risotto",
                            Ingredients = "olive oil | onion | garlic | spring onions | rice | cumin | parmesan | gorgonzola | scallop | cream"
                        },
                        new
                        {
                            DishId = 48,
                            DishDescription = "Seaweed and gammon served on a bed of lettuce",
                            DishName = "Seaweed and gammon salad",
                            Ingredients = "lettuce | seaweed | gammon"
                        },
                        new
                        {
                            DishId = 49,
                            DishDescription = "Warm ciabatta filled with fresh banana and yellow grapefruit",
                            DishName = "Banana and grapefruit ciabatta",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | banana | grapefruit"
                        },
                        new
                        {
                            DishId = 50,
                            DishDescription = "Fresh egg pasta in a sauce made from dolcelatte and lea bacon",
                            DishName = "Dolcelatte and bacon pasta",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | dolcelatte | bacon"
                        },
                        new
                        {
                            DishId = 51,
                            DishDescription = "Spagetti topped with a blend of bresaola and fresh broccoli",
                            DishName = "Bresaola and broccoli spaghetti",
                            Ingredients = "tomato | passata | onion | garlic | spagetti | oregano | black pepper | bresaola | broccoli"
                        },
                        new
                        {
                            DishId = 52,
                            DishDescription = "A warm bagel filled with bell pepper and steak",
                            DishName = "Pepper and steak bagel",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | pepper | steak"
                        },
                        new
                        {
                            DishId = 53,
                            DishDescription = "Smoked turkey and minced lamb stewed",
                            DishName = "Turkey and lamb stew",
                            Ingredients = "onion | salt | black pepper | potatoes | turkey | lamb"
                        },
                        new
                        {
                            DishId = 54,
                            DishDescription = "Black mustard seeds and dried chilli served on a bed of lettuce",
                            DishName = "Mustard seed and chilli salad",
                            Ingredients = "lettuce | mustard seed | chilli"
                        },
                        new
                        {
                            DishId = 55,
                            DishDescription = "Crisp slices of bread filled with corn-fed chicken and fresh avocado",
                            DishName = "Chicken and avocado toastie",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | chicken | avocado"
                        },
                        new
                        {
                            DishId = 56,
                            DishDescription = "Thin wonton cases stuffed with crisp apple and green cardamom",
                            DishName = "Apple and cardamom wontons",
                            Ingredients = "flour | water | salt | sugar | apple | cardamom"
                        },
                        new
                        {
                            DishId = 57,
                            DishDescription = "A shortcrust pasty case filled with mature cheese and beef",
                            DishName = "Cheese and beef pie",
                            Ingredients = "flour | butter | water | salt | sugar | cheese | beef"
                        },
                        new
                        {
                            DishId = 58,
                            DishDescription = "Fluffy bread made with sea salt and cinnamon",
                            DishName = "Salt and cinnamon bread",
                            Ingredients = "flour | salt | yeast | butter | water | onions | cinnamon"
                        },
                        new
                        {
                            DishId = 59,
                            DishDescription = "A crunchy salad featuring fresh spring onion and frangelico",
                            DishName = "Spring onion and frangelico salad",
                            Ingredients = "cucumber | tomato | white cabbage | spring onion | frangelico"
                        },
                        new
                        {
                            DishId = 60,
                            DishDescription = "A crisp salad featuring bean and cashew",
                            DishName = "Bean and cashew salad",
                            Ingredients = "cucumber | lettuce | cress | bean | cashew"
                        },
                        new
                        {
                            DishId = 61,
                            DishDescription = "Skewer-cooked streaky bacon and smoked turkey served in warm pitta pockets",
                            DishName = "Bacon and turkey kebab",
                            Ingredients = "onions | flour | yeast | water | salt | sugar | oil | bacon | turkey"
                        },
                        new
                        {
                            DishId = 62,
                            DishDescription = "Thin and crispy pizza topped with polenta and smoked ham",
                            DishName = "Polenta and ham pizza",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | cheese | polenta | ham"
                        },
                        new
                        {
                            DishId = 63,
                            DishDescription = "Fresh egg pasta in a sauce made from caper and tangy lemon",
                            DishName = "Caper and lemon pasta",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | caper | lemon"
                        },
                        new
                        {
                            DishId = 64,
                            DishDescription = "Fresh egg pasta in a sauce made from sun-dried tomato pesto and minced lamb",
                            DishName = "Pesto and lamb pasta",
                            Ingredients = "tomato | onion | garlic | pasta | oregano | black pepper | pesto | lamb"
                        },
                        new
                        {
                            DishId = 65,
                            DishDescription = "Creamy korma made with fresh cauliflower and dried mango",
                            DishName = "Cauliflower and mango korma",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | cauliflower | mango"
                        },
                        new
                        {
                            DishId = 66,
                            DishDescription = "Hot slices of bread filled with crayfish and crispy tofu",
                            DishName = "Crayfish and tofu toastie",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | crayfish | tofu"
                        },
                        new
                        {
                            DishId = 67,
                            DishDescription = "Bamboo skewers loaded with baby new potato and minced lamb",
                            DishName = "Potato and lamb skewers",
                            Ingredients = "onions | potato | lamb"
                        },
                        new
                        {
                            DishId = 68,
                            DishDescription = "Swordfish and tangy feta served on a bed of lettuce",
                            DishName = "Swordfish and feta salad",
                            Ingredients = "lettuce | swordfish | feta"
                        },
                        new
                        {
                            DishId = 69,
                            DishDescription = "Mild korma made with minced lamb and fresh cod",
                            DishName = "Lamb and cod korma",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | lamb | cod"
                        },
                        new
                        {
                            DishId = 70,
                            DishDescription = "Thin and crispy pizza topped with fresh marjoram and tuna",
                            DishName = "Marjoram and tuna pizza",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | cheese | marjoram | tuna"
                        },
                        new
                        {
                            DishId = 71,
                            DishDescription = "A flaky pasty case filled with crisp apple and wild rice",
                            DishName = "Apple and rice pie",
                            Ingredients = "flour | butter | water | salt | onions | apple | rice"
                        },
                        new
                        {
                            DishId = 72,
                            DishDescription = "A crisp salad featuring goose and green cabbage",
                            DishName = "Goose and green cabbage salad",
                            Ingredients = "white cabbage | tomato | lettuce | goose | green cabbage"
                        },
                        new
                        {
                            DishId = 73,
                            DishDescription = "Fluffy bread made with polenta and creamy butter",
                            DishName = "Polenta and butter loaf",
                            Ingredients = "flour | salt | yeast | butter | water | onions | polenta"
                        },
                        new
                        {
                            DishId = 74,
                            DishDescription = "Pectin and ragu served on a bed of lettuce",
                            DishName = "Pectin and ragu salad",
                            Ingredients = "lettuce | pectin | ragu"
                        },
                        new
                        {
                            DishId = 75,
                            DishDescription = "Pasta in a sauce made from fresh avocado and red pepper",
                            DishName = "Avocado and pepper uramaki",
                            Ingredients = "rice | rice vinegar | sugar | avocado | pepper"
                        },
                        new
                        {
                            DishId = 76,
                            DishDescription = "Shitake mushroom and olive stewed",
                            DishName = "Mushroom and olive stew",
                            Ingredients = "onion | salt | black pepper | potatoes | mushroom | olive"
                        },
                        new
                        {
                            DishId = 77,
                            DishDescription = "A crisp salad featuring creole seasoning and boar",
                            DishName = "Creole seasoning and boar salad",
                            Ingredients = "lettuce | tomato | cucumber | creole seasoning | boar"
                        },
                        new
                        {
                            DishId = 78,
                            DishDescription = "Skewer-cooked smoked tofu and duck served in warm pitta pockets",
                            DishName = "Tofu and duck kebab",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | tofu | duck"
                        },
                        new
                        {
                            DishId = 79,
                            DishDescription = "A crunchy salad featuring radiatori and flaxseeds",
                            DishName = "Radiatori and flaxseed salad",
                            Ingredients = "tomato | lettuce | cucumber | radiatori | flaxseed"
                        },
                        new
                        {
                            DishId = 80,
                            DishDescription = "Fresh lemon and celery combined into smooth soup",
                            DishName = "Lemon and celery soup",
                            Ingredients = "garlic | lemon | celery"
                        },
                        new
                        {
                            DishId = 81,
                            DishDescription = "Mild korma made with fresh plantain and duck",
                            DishName = "Plantain and duck korma",
                            Ingredients = "onion | peppers | garlic | ginger | tumeric | cumin | coriander | butter | sugar | cream | plantain | duck"
                        },
                        new
                        {
                            DishId = 82,
                            DishDescription = "Stem ginger and fresh celery stewed",
                            DishName = "Ginger and celery casserole",
                            Ingredients = "onion | salt | black pepper | potatoes | ginger | celery"
                        },
                        new
                        {
                            DishId = 83,
                            DishDescription = "Fresh cranberries and cajun seasoning served on a bed of lettuce",
                            DishName = "Cranberry and cajun seasoning salad",
                            Ingredients = "lettuce | cranberry | cajun seasoning"
                        },
                        new
                        {
                            DishId = 84,
                            DishDescription = "Crunchy bread made with creamy cheese and fresh raisin",
                            DishName = "Cheese and raisin bread",
                            Ingredients = "flour | salt | yeast | butter | water | onions | cheese | raisin"
                        },
                        new
                        {
                            DishId = 85,
                            DishDescription = "A crisp salad featuring goosnargh and sharon fruit",
                            DishName = "Goosnargh and sharon fruit salad",
                            Ingredients = "cress | white cabbage | lettuce | goosnargh | sharon fruit"
                        },
                        new
                        {
                            DishId = 86,
                            DishDescription = "Crunchy stir fry featuring fresh wasabi and mangetout",
                            DishName = "Wasabi and mangetout stir fry",
                            Ingredients = "garlic | wasabi | mangetout"
                        },
                        new
                        {
                            DishId = 87,
                            DishDescription = "Root ginger and shrimp combined into chunky soup",
                            DishName = "Ginger and shrimp soup",
                            Ingredients = "onion | ginger | shrimp"
                        },
                        new
                        {
                            DishId = 88,
                            DishDescription = "Crunchy stir fry featuring spiced pumpkin and fresh chickpea",
                            DishName = "Pumpkin and chickpea stir fry",
                            Ingredients = "garlic | pumpkin | chickpea"
                        },
                        new
                        {
                            DishId = 89,
                            DishDescription = "A warm bagel filled with pork and fresh cucumber",
                            DishName = "Pork and cucumber bagel",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | pork | cucumber"
                        },
                        new
                        {
                            DishId = 90,
                            DishDescription = "Crunchy bread made with tea and fresh yeast",
                            DishName = "Tea and yeast bread",
                            Ingredients = "flour | salt | yeast | butter | water | onions | tea"
                        },
                        new
                        {
                            DishId = 91,
                            DishDescription = "Garlic powder and fresh star fruit served on a bed of lettuce",
                            DishName = "Garlic powder and star fruit salad",
                            Ingredients = "lettuce | garlic powder | star fruit"
                        },
                        new
                        {
                            DishId = 92,
                            DishDescription = "Thin wonton cases stuffed with fresh jalapeno and hot chilli",
                            DishName = "Jalapeno and chilli wontons",
                            Ingredients = "flour | water | salt | onions | jalapeno | chilli"
                        },
                        new
                        {
                            DishId = 93,
                            DishDescription = "Warm ciabatta filled with fresh jalapeno and cucumber",
                            DishName = "Jalapeno and cucumber ciabatta",
                            Ingredients = "flour | yeast | water | salt | sugar | oil | jalapeno | cucumber"
                        },
                        new
                        {
                            DishId = 94,
                            DishDescription = "Turbot and serrano ham served on a bed of lettuce",
                            DishName = "Turbot and serrano ham salad",
                            Ingredients = "lettuce | turbot | serrano ham"
                        },
                        new
                        {
                            DishId = 95,
                            DishDescription = "A crisp salad featuring caramel sauce and gorgonzola",
                            DishName = "Caramel sauce and gorgonzola salad",
                            Ingredients = "cress | tomato | cucumber | caramel sauce | gorgonzola"
                        },
                        new
                        {
                            DishId = 96,
                            DishDescription = "A crunchy salad featuring parma ham and samphire",
                            DishName = "Parma ham and samphire salad",
                            Ingredients = "cress | lettuce | white cabbage | parma ham | samphire"
                        },
                        new
                        {
                            DishId = 97,
                            DishDescription = "Thin pastry cases stuffed with fish and fresh mushroom",
                            DishName = "Fish and mushroom dumplings",
                            Ingredients = "flour | water | salt | onions | fish | mushroom"
                        },
                        new
                        {
                            DishId = 98,
                            DishDescription = "Fluffy bread made with fresh pumpkin and squash",
                            DishName = "Pumpkin and squash bread",
                            Ingredients = "flour | salt | yeast | butter | water | onions | pumpkin | squash"
                        },
                        new
                        {
                            DishId = 99,
                            DishDescription = "Fresh plantain and pork stewed",
                            DishName = "Plantain and pork stew",
                            Ingredients = "onion | salt | black pepper | potatoes | plantain | pork"
                        },
                        new
                        {
                            DishId = 100,
                            DishDescription = "A crunchy salad featuring wheat and French mustard",
                            DishName = "Wheat and mustard salad",
                            Ingredients = "white cabbage | tomato | cucumber | wheat | mustard"
                        });
                });

            modelBuilder.Entity("FoodLibrary.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DishDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
